# Use root/example as user/password credentials
version: '3.1'

networks:
    3r:
        driver: bridge

services:

    db:
        image: mysql
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        networks:
            - 3r

    elasticsearch:
        image: elasticsearch:8.6.0
        environment:
            - discovery.type=single-node
            - node.name=3r-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
            - xpack.security.enrollment.enabled=false
            - xpack.security.http.ssl.enabled=false
            - xpack.security.transport.ssl.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - 3r

    kibana:
        image: kibana:8.6.0
        environment:
            - I18N_LOCALE=zh-CN
            - XPACK_GRAPH_ENABLED=true
            - TIMELION_ENABLED=true
            - XPACK_MONITORING_COLLECTION_ENABLED="true"
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        networks:
            - 3r
